### ISSUE TITLE
transcript gerekiyor

### ISSUE THREAD

**Issue by ybrs** [azmesai/faruk-sengul-kinama#1]
konusmalar cok uzun, hepsini dinlemek yerine transcript bulunabilir/yaptirilabilir/yapilabilir ise, neden kinandigina dair daha saglam bir temel olusacaktir diye dusunuyorum.

**Comment by ybrs** [comment]
usenmedim izledim ya hepsini sabahin korunde, ozet geciyorum hizlica konuya dahil olmak isteyenler icin. daha sonra kendi yorumlarim icin ayrica pull request gonderecegim.

2.inci videonun 15inci dakikasindan basliyor asil olay, oraya gelene kadar gayet arogan, "siz zaten bisey bilmiyorsunuz", "bizim sektor sabah 8 aksam 5 degil", "youtubedan vidyo izleyip her seyi ogrenebilirsiniz ama yapmiyorsunuz" tavri var ama tavir haricinde soylediklerinde cok ta fena bir durum yok. yalniz tavir oldukca, fazlasiyla yanlis onu soylemeden gecemeyecegim.

sonrasinda olay, bir ogrencinin, "kadin yazilimcilar hakkinda ne dusunuyorsunuz" gibi bir sorusu uzerine gelisiyor iyice, "ya **bayan** yazilimcinin vakitle sikintisi var ", "erkek yazilimci isi yetistiremezse saydiriyorsun, ama bayana saydiramiyorsun eyk eyk cok komik", "is sorumlulugu alma konusunda 100 bayan yazilimci varsa, 2-3 kiside cikar", "ya bir saat daha fazla calis diyorsun, eve gidecegim diyor" diye ilerliyor.

merak edenler 2inci videonun sonlarina dogru baslayip, 3uncu videonun ortasinda birakabilirler. contexti anlamak icin tamamini izlemek daha faydali olacaktir diye dusunuyorum.

**Comment by gokaygurcan** [comment]
@eserozvataf 'ı da ping'lemeyi unutmayın. 
https://github.com/eserozvataf/kontra-is-anlasmasi

**Comment by muratcorlu** [comment]
Videoların linklerini de paylaşmakta fayda var.

**Comment by leventyalcin** [comment]
@muratcorlu  video linklerini @ybrs ekledi. uyari icin tesekkurler

**Comment by leventyalcin** [comment]
@gulcin transcript icin yardimci olma sansin var mi?

**Comment by gulcin** [comment]
@leventyalcin ilk izlerken zor izledim, sinirlerimi bozuyor bir daha izleyemiyorum :( ben wikiyi ingilizceye fln cevireyim bi ise yarayacaksa ama bu videoyu bir daha izlemeyeyim :(

**Comment by leventyalcin** [comment]
@gulcin yapmayi isteyip istememek senin kararin amma velakin gozlerini yumarak canavarin gitmesini beklemek iyi bir yaklasim mi onu bilemedim

**Comment by gulcin** [comment]
haklisin @leventyalcin ikinci video 15:20'den itibaren basladim.

**Comment by gulcin** [comment]
bu isi bana atayabilirsiniz. @ybrs @leventyalcin

**Comment by leventyalcin** [comment]
@ybrs yeterli mi yoksa sektorle ya da insanla ilgili genel yaklasim bozukluklari ile ilgili kisimlari da net gorelim der misin?

**Comment by ybrs** [comment]
@leventyalcin abi bence gayet yeterli, zaten can alici yeri var transcriptte, devam etmek isteyen videoyu izleyebilir. Zira genel ruh halininin anlasilmasi icin bence videonun muhakkak izlenmesi gerekiyor.

@gulcin tesekkurler

**Comment by gulcin** [comment]
rica ederim @ybrs . bugun de calisiyorum, vakit bulayim sahneden indigi kisma kadar olan yeri yazicam.
