### ISSUE TITLE
Repo ismi

### ISSUE THREAD

**Issue by eser** [azmesai/faruk-sengul-kinama#12]
İsimdeki yazım hatası nedeniyle repo'nun ismini değiştirmek gerekli mi dersiniz?

**Comment by leventyalcin** [comment]
sagda soldaki postlarda link oldugu icin yapmadim ama degistireyim

**Comment by leventyalcin** [comment]
benim postum haricinde link var sozluk'te. o yuzden degistirmesek daha iyi diye dusunuyorum. :+1:  ya da :-1: alabilirsek bunun icin cok iyi olur

**Comment by f** [comment]
Repo adını değiştirdiğinizde GitHub eski adı yönlendirme yapıyor. Bu açıdan sorun oluşmayacak.

**Comment by leventyalcin** [comment]
@f bunu bilmiyordum. super oldu. cok tesekkurler. 
repo adini da degistirdim.
