### ISSUE TITLE
Kinama mektubunun son haline gelmesi ve Change.org'da yayinlanmasi

### ISSUE THREAD

**Issue by leventyalcin** [azmesai/faruk-sengul-kinama#24]

**Comment by leventyalcin** [comment]
Tum katki saglayan arkadaslar. https://github.com/azmesai/faruk-sengun-kinama/blob/master/taslak.md icin yorum, katki, PR'larinizi gonderebilirseniz sevinirim. 

@gulcin @eserozvataf @oguzalb @fatiherikli @ybrs @erayaydin @dashersw @burakcan @gurkanoluc  @gokaygurcan @fg @smtaydemir @delirehberi @f

**Comment by leventyalcin** [comment]
@broccolinisoup Sen PR gonderdigin sirada taslak yaziyi cikariyordum, o yuzden simdi gordum. Gordugum kadariyla anlattigin noktalardan kacirdigim bir sey yok. Taslak yaziyi da gozden gecirebilir ve katkida bulunabilirsen sevinirim

**Comment by broccolinisoup** [comment]
Pazar gunu okudugumda birkac yer dikkatimi cekmisti ama gordugum kadariyla oralar degistirilmis. Simdi okuyunca hicbir yere takilmadim gayet guzel olmus bence. Farkli bir tarz olmus bu arada kim baslattiysa tesekkurler. Ne zaman yayimlayacagiz change.org'da?

**Comment by eser** [comment]
Turkce harfleri kullanmamiz gerekli diye dusunuyorum.

**Comment by oguzalb** [comment]
katiliyorum

**Comment by leventyalcin** [comment]
@broccolinisoup en kisa zamanda, bugun en son bir iki rotus ile +1 alirsa gondermeyi dusunuyordum ama inanilmaz hastayim, bir iki gun gecikebilir.

**Comment by leventyalcin** [comment]
@eserozvataf @oguzalb en son Turkce karakterler ile koyacagiz kesinlikle.

**Comment by leventyalcin** [comment]
@eserozvataf Turkce karakterler tamam

**Comment by leventyalcin** [comment]
@wizard @dashersw @arslanbilal @cansusezen @dnomak @emir @delirehberi @erayaydin @fatiherikli @fg @halitalptekin @keremciu @mihriminaz @oguzhanaslan @slmcncb 

Suraya da bir imza alabilir miyiz? https://www.change.org/p/faruk-argede-com-tr-cinsiyet%C3%A7i-ve-i%C5%9F-ahlak%C4%B1na-ayk%C4%B1r%C4%B1-konu%C5%9Fmas%C4%B1ndan-%C3%B6t%C3%BCr%C3%BC-faruk-%C5%9Feng%C3%BCn-e-%C3%B6z%C3%BCr-%C3%A7a%C4%9Fr%C4%B1s%C4%B1d%C4%B1r-a489d069-fcf8-4c1b-9129-19808d494c95/dashboard

**Comment by leventyalcin** [comment]
Pardon, dashboard olmadan :)

https://www.change.org/p/faruk-argede-com-tr-cinsiyet%C3%A7i-ve-i%C5%9F-ahlak%C4%B1na-ayk%C4%B1r%C4%B1-konu%C5%9Fmas%C4%B1ndan-%C3%B6t%C3%BCr%C3%BC-faruk-%C5%9Feng%C3%BCn-e-%C3%B6z%C3%BCr-%C3%A7a%C4%9Fr%C4%B1s%C4%B1d%C4%B1r-a489d069-fcf8-4c1b-9129-19808d494c95

**Comment by phpdev** [comment]
Change.org'da video ve metin yer alsaydı daha güzel olurdu konuyu bilmeyen birisi ne olduğunu anlamalı. 
Ayrıca change.org'da öne çıkan görsel olmadığı için facebook'ta thumbnail gözükmüyor gözükse daha dikkat çekici olabilir paylaşım yaptığımızda.

**Comment by leventyalcin** [comment]
Updatelerde linkleeri var. eger videolari kesip ilgili kisimlari
birlestiren olursa kampanyaya ekleyebilirim

On Tuesday, March 22, 2016, Selim Can CABA notifications@github.com wrote:

> Change.org'da video ve metin yer alsaydı daha güzel olurdu konuyu bilmeyen
> birisi ne olduğunu anlamalı.
> Ayrıca change.org'da görsel olmadığı için facebook'ta thumbnail
> gözükmüyor gözükse daha dikkat çekici olabilir paylaşım yaptığımızda.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/azmesai/faruk-sengun-kinama/issues/24#issuecomment-199745186

## 

Levent YALCIN
DevOps
http://about.me/leventyalcin

**Comment by phpdev** [comment]
İlgili kısım kesildi: https://www.youtube.com/watch?v=lsudyXNgYlw

**Comment by leventyalcin** [comment]
@slmcncb, Videoyu ekledim. Gozune ilisen baska bir sey var mi?

**Comment by phpdev** [comment]
@leventyalcin Şu an için yok, video eklenince görselde gelmiş.

**Comment by leventyalcin** [comment]
OK'dir. Su an icin issue'yu kapatiyorum. Yardimin icin tesekkurler.
